# Arrays pregenerados

## Arrays de ceros:
Podemos generar arrays de 0s

Métdo **zeros()**

In [1]:
import numpy as np

np.zeros(4)

array([0., 0., 0., 0.])

Ahora, pero de dos dimensiones

In [3]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Arrays de unos

Método **ones()**

In [4]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Arrays de identidad (muy usado en videojuegos):

Son matrices cuadradas ( número de filas = número de columnas), donde todos los valores son ceros, exceptuando la diagonal que son unos. Usamos el método **eye()**

Por ejemplo usado para randerizar datos etc.

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Arrays de rangos

Vamos a generar un array a partir de un rango de valores. Vamos a usar el método **arrange()** (siempre es el valor -1)

In [8]:
# Rango de 0 a 5 entero
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
# Rango de 0 a 5 decimal
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [10]:
# De valores negativos, de -5 a 5
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

Le podemos dar el paso:

In [12]:
np.arange(0, 21, 5) # con paso de 5

array([ 0,  5, 10, 15, 20])