# Manejo de arrays

Igual que en las colecciones, tenemos que tener en cuenta el índice

## Índice de las arrays
Las arrays funcionan igual que cualquier colección de Python, podemos acceder a cada uno de los elementos usando el índice que tienen.

In [14]:
import numpy as np
arr = np.arange(0,50,5)

print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [15]:
# Primera posición 
print(arr[0])
# Última posición
print(arr[-1])

0
45


In [16]:
# Asignación de valor
arr[-1] = 99
print(arr)

[ 0  5 10 15 20 25 30 35 40 99]


## Slicing
Como cuando haciamos con las colecciones

In [17]:
# Copia completa, índices vacíos
arr[:]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 99])

In [18]:
# Subarray de los 3 primeros elementos
arr[:3]

array([ 0,  5, 10])