# Funciones universales

- Operaciones matemáticas
- Operaciones trigonométricas
- Operaciones comparativas
- Operaciones flotantes

## Matemáticas

In [104]:
import numpy as np

# arrays de prueba
arr_1 = np.arange(1,6)
arr_2 = np.array([-3,7,3,13,0])
print(arr_1)
print(arr_2)

[1 2 3 4 5]
[-3  7  3 13  0]


In [105]:
#suma o adición
np.add(arr_1,arr_2)

array([-2,  9,  6, 17,  5])

In [106]:
# resta por subtracción
np.subtract(arr_1, arr_2)

array([ 4, -5,  0, -9,  5])

In [107]:
# raiz cuadrada
np.sqrt(arr_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [108]:
# potencia
np.power(arr_2, 3)

array([ -27,  343,   27, 2197,    0])

In [109]:
# signo
np.sign(arr_2) # 1 = positivo, -1 = negativo y 0 = cero

array([-1,  1,  1,  1,  0])

## Trigonométricas

In [110]:
# seno
np.sin(arr_1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [111]:
# coseno
np.cos(arr_1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [112]:
# tangente
np.tan(arr_1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [113]:
# grados a radianes
np.deg2rad(arr_1)

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [114]:
# radianes a grados
np.rad2deg(arr_1)

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
       286.47889757])

## Comparativas

In [115]:
# máximo
np.maximum(arr_1, arr_2)

array([ 1,  7,  3, 13,  5])

In [116]:
# mínimo
np.minimum(arr_1, arr_2)

array([-3,  2,  3,  4,  0])

In [117]:
# igualdad
np.equal(arr_1, arr_2) # devuelve true o false

array([False, False,  True, False, False])

In [118]:
# mayor que
np.greater(arr_1, arr_2) # devuelve true o false

array([ True, False, False, False,  True])

## Flotantes

In [119]:
# tercer array de prueba
arr_3 = np.array([3.14, 2.57, -6.4, 0.47, 5.5])

In [120]:
# valor absoluto
np.fabs(arr_3)

array([3.14, 2.57, 6.4 , 0.47, 5.5 ])

In [121]:
# techo (redondeo entero al alza)
np.ceil(arr_3)

array([ 4.,  3., -6.,  1.,  6.])

In [122]:
# suelo (redondeo entero a la baja)
np.floor(arr_3)

array([ 3.,  2., -7.,  0.,  5.])