# Funciones aleatorias

Dentro de numpy generar array aleatorios y aleatorios con permutaciones

## Generando datos aleatorios

In [27]:
import numpy as np

In [28]:
# número decimal entre 0 y 1
np.random.rand()

0.04068838205606329

In [29]:
# generando un vector o array 1D entre 0 y 1
np.random.rand(4)

array([0.46506579, 0.10330972, 0.36423317, 0.62970856])

In [30]:
# generar un array 2D de decimales entre 0 y 1
np.random.rand(4,2) # elementos, dimensiones

array([[0.87281555, 0.23869883],
       [0.16386155, 0.66640859],
       [0.23641526, 0.44384001],
       [0.74814663, 0.39019426]])

In [31]:
# generar un array 3D de decimales entre 0 y N
np.random.uniform(10, size= [3,3,3]) # generas una array con numeros random y le pasas las dimensiones del array

array([[[9.69996662, 4.71594485, 4.1976361 ],
        [5.45440864, 3.66326759, 2.28028219],
        [5.31608779, 2.2319478 , 9.65529709]],

       [[6.33520543, 9.84414177, 5.86223014],
        [2.81968417, 8.15836868, 3.85432846],
        [5.13290234, 4.70580513, 4.00060015]],

       [[3.43557136, 8.71731998, 2.23319992],
        [4.38699387, 9.58248446, 7.50492354],
        [3.32341055, 1.37254311, 8.41908412]]])

In [32]:
# generar un array 4D de decimales en -N y N
np.random.uniform(-10, 10,  size=[2,2,2,2])

array([[[[ 6.89783705,  6.99235563],
         [-8.6001626 ,  2.32076577]],

        [[-8.50718997,  2.49973686],
         [ 6.06923456, -9.57384197]]],


       [[[ 8.16544533, -7.52764447],
         [ 0.3280514 ,  9.92113087]],

        [[ 2.12945746,  9.05321928],
         [ 8.48005539,  5.6995457 ]]]])

In [33]:
# Número entero entre 0 y N
np.random.randint(10)

7

In [34]:
#array de enteros entre 0 y N
np.random.randint(10, size = [3,2])

array([[2, 5],
       [1, 9],
       [1, 6]], dtype=int32)

In [35]:
# array de enteros entre -N y N
np.random.randint(-10, 10, size= [3,2])

array([[-5,  9],
       [-8, -9],
       [-1,  8]], dtype=int32)

In [36]:
# array uniforme = campana de gauss, con curva gausiana
np.random.normal(size=20) # es un vector

array([-0.63396211, -0.27315745, -0.52990164,  0.07538758,  0.20388475,
        0.40825255, -1.03007319,  2.57303675,  0.61732373,  0.10417035,
       -1.79730838,  1.51962024,  1.39185676, -0.6828428 , -0.33963651,
       -0.59829837, -0.63580803, -1.07369919, -0.14004954, -0.14559162])

## Permutaciones

In [37]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# desordenar un array
np.random.shuffle(arr)
arr

array([3, 0, 2, 9, 5, 8, 4, 1, 7, 6])

In [39]:
# generar una secuencia permutada a partir de un número
np.random.permutation(15) # esto sería hacer un range + shuffle

array([ 6, 10,  4,  0, 11,  9,  8,  7,  2,  5, 14,  3, 12, 13,  1],
      dtype=int32)