# Filtrado de arrays

## Filtro *unique*
borra todos los elementos duplicados. Devuelve un array de una dimensión borrando todos los elementos duplicados.

In [65]:
import numpy as np

In [66]:
# generamos un array de enteros aleatorios repetidos
arr = np.random.randint(0,10,40)
arr

array([1, 1, 4, 1, 6, 4, 9, 2, 6, 3, 7, 0, 5, 0, 5, 0, 5, 7, 7, 0, 9, 1,
       2, 7, 8, 8, 1, 0, 0, 1, 7, 3, 1, 7, 9, 7, 0, 5, 7, 2], dtype=int32)

In [67]:
# aplicamos el filtro
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

## Filtro *in1d*
Devuelve un array de una dimensión, indicando si los elementos de una lista se encutntran en otro array.

In [68]:
# np.in1d([-1,4,8,12], arr)
np.isin([-1,4,8,12], arr)

array([False,  True,  True, False])

## Filtro *where*
Genera un array filtrando a partir de una condición y un valor por defecto

In [69]:
# generamos un array con números aleatorios decimales
arr_1 = np.random.uniform(-5,5, size=[3,2])
arr_1

array([[ 1.2208647 , -4.66065681],
       [ 4.63838764, -2.95214746],
       [-0.60931098,  3.08446877]])

In [70]:
# creamos un filtro que establece los negativos a 0
arr_2 = np.where(arr_1 < 0, 0, arr_1)
arr_2

array([[1.2208647 , 0.        ],
       [4.63838764, 0.        ],
       [0.        , 3.08446877]])

In [71]:
# creamos un filtro para los positivos sean 1
arr_2 = np.where(arr_2 >0, True, arr_2) # True = 1
arr_2

array([[1., 0.],
       [1., 0.],
       [0., 1.]])

## Filtros booleanos
comprovaciones logicas en los arrays de booleans

Permite hacer comprovaciones lógicas en lso arrays booleanos

In [72]:
# definimos un array de booleanos
arr_bool = np.array([True, True, True, False])

In [73]:
# comprobar si todos los elementos del array son true
arr_bool.all()

np.False_

In [74]:
# comprobar si al menos un elemento es True
arr_bool.any()

np.True_

In [75]:
# array de booleanos de 2D
arr_bool_2D = np.array(
    [
        [False, True],
        [False, True],
        [False, True],
    ]
)

print(arr_bool_2D.all())
print(arr_bool_2D.all(0)) # comprobando columnas
print(arr_bool_2D.all(1)) # comprobando filas si almenos hay un True

False
[False  True]
[False False False]


## Métodos internos

## Métodos estadísticos

In [76]:
import numpy as np

# generamos un array 2x3 con números enteros(rango 1 al 7)

arr = np.arange(1,7).reshape(2,3)
arr 

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
# Sumatorio de los valores del array
arr.sum()

np.int64(21)

In [78]:
# media aritmética de los valores del array
arr.mean()

np.float64(3.5)

In [79]:
# desviación estandar
arr.std() # indica si los valores están dispersos o cerca entre sí

np.float64(1.707825127659933)

In [80]:
# varianza
arr.var() # es el cuadrado de la desviación estándar

np.float64(2.9166666666666665)

## Métodos de ordenación

In [82]:
# generamos un array aleaorio de números enteros
arr = np.random.randint(-10,10, [3,3])
arr

array([[  1,   5, -10],
       [  8,  -8,   4],
       [ -8,   8,   1]], dtype=int32)

In [83]:
# ordenar los elementos horizontales
arr.sort()
arr

array([[-10,   1,   5],
       [ -8,   4,   8],
       [ -8,   1,   8]], dtype=int32)

In [84]:
# ordenar los elementos verticalmente
arr.sort(0)
arr

array([[-10,   1,   5],
       [ -8,   1,   8],
       [ -8,   4,   8]], dtype=int32)