# Operaciones básicas

## Suma y resta
para poder sumar y restar arrays, tienen que tener la misma forma.

para realizar la suma o la resta de arrays, éstas tienen que tener las mismas dimensiones y tamaño.

In [3]:
import numpy as np

# Creamos dos arrays

arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

# Suma

print(arr_1 + arr_2)

# Resta

print(arr_1 - arr_2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]


In [4]:
# Array de una forma distinta (da error)

arr_3 = np.array([11,12])

# Suma o resta

print(arr_1 + arr_3)

print(arr_2 - arr_3)

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

## Producto
También tiene que coincidir el número de elementos aquí

In [5]:
# Creamos dos arrays
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])

arr_1 * arr_2

array([ 6, 14, 24, 36, 50])

Multiplicarla por un número concreto:

In [6]:
arr_1 * 10

array([10, 20, 30, 40, 50])

## División

In [8]:
arr_1 / arr_2 # devuelve, en este caso, array con decimales

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
# Dividimos todos los elementos entra un número
arr_1 / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [10]:
#Inversa de un array
1 / arr_1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

## Potencia

In [11]:
arr_1 ** arr_2

array([      1,     128,    6561,  262144, 9765625])

## Operaciones con arrays de 2D (2 dimensiones)

In [13]:
# Declaramos dos arrays de 2D
arr_5 = np.array(
    [
        [1,2],
        [3,4]
    ]
)

arr_6 = np.array(
    [
        [5,6],
        [7,8]
    ]
)

# Sumamos las dos arrays
arr_5 + arr_6

array([[ 6,  8],
       [10, 12]])

coge el primero con el primer, el segundo con el segundo y te devuelve la primera sublista y luego el segundo con el segundo y te genera la segunda sublista

In [15]:
# Producto, división y potencia con un número
print(arr_5 * 4)
print(arr_6 / 2)
print(arr_5 ** 2)

[[ 4  8]
 [12 16]]
[[2.5 3. ]
 [3.5 4. ]]
[[ 1  4]
 [ 9 16]]


In [16]:
#Operación de array de 2D para crear un vector. Da error porqué tiene dimensiones distintas

arr_5 * np.array([5,6,7,8])

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 