# Arrays multidimensionales

## Índices de 2D (2 Dimensiones)

In [46]:
import numpy as np

arr_2d = np.array(
    [
        [0,5,10],
        [15,20,25],
        [30,35,40]
    ])

arr_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [47]:
# Llamamos al índice de la primera fila
arr_2d[0]

array([ 0,  5, 10])

In [48]:
# Primera fila primera columna
arr_2d[0][0] # lo que hay entre paraentesis es el valor

np.int64(0)

In [49]:
#última fila de la ultima columna
arr_2d[-1][-1] # "son el eje X y el eje Y de la tabla"

np.int64(40)

## Slicing de 2D
 pones los indices y los separas por coma. Para hacer slicing en tablas o arrays 2D, doblamos los índices de inicio y fin separándolos con comas

In [50]:
# Subarray con todas las filas y columnas
arr_2d[:,:] #El primer dato son filas y el segundo columnas

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [51]:
# Subarray de las dos primeras filas
arr_2d[:2,:]

array([[ 0,  5, 10],
       [15, 20, 25]])

In [52]:
# subarray de la primera columna
arr_2d[:,:1]

array([[ 0],
       [15],
       [30]])

Se pueden pasar bucles for etc, como si fueran colecciones

## Arrays 3D y más dimensiones

Para trabajar con arrays de más de 2 dimensiones vamos a anidar niveles de profundidad

Vamos a crear un array 3D paso a paso

In [53]:
import numpy as np

# primer nivel
arr_1d = np.array([1,2])

arr_1d

array([1, 2])

In [54]:
# segundo nivel (2 x 2 = 4 elementos)
arr_2d = np.array(
    [
        [1,2],
        [3,4]
    ])

arr_2d

array([[1, 2],
       [3, 4]])

In [55]:
# tercer nivel (2 x 2 x 2 = 8 elementos)
arr_3d = np.array(
    [
        [
            [1,2],
            [3,4]
        ],
        [
            [5,6],
            [7,8] 
        ]
    ]
)

arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
# cuarto nivel (2 x 2 x 2 x 2 = 16 elementos)
arr_4d = np.array(
    [
        [
            [
                [1,2],
                [3,4]
            ]
        ],
        [
            [
                [5,6],
                [7,8] 
            ]
        ],
        [
            [
                [9,10],
                [11,12]
            ]
        ],
        [
            [
                [13,14],
                [15,16] 
            ]
        ]
    ]
)
arr_4d

array([[[[1, 2],
         [3, 4]]],


       [[[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]]],


       [[[5, 6],
         [7, 8]]]])

In [57]:
# array pregenerada de ceros
arr_3d = np.zeros([3,3,3])
arr_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
# array pregenerada de unos de 4D
arr_4d = np.ones([4,4,4,4])
arr_4d

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

      

Podemos usar **reshape()** para reformar dimensiones y tamaños

In [59]:
# reshape de un rango con 9 elementos en una matriz de 3 x 3
arr_2d = np.arange(9).reshape(3,3) # de 3 dimensiones ?
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
# reshape de 27 elementos 3 x 3 x 3
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
# generando un array de 3 dimensiones de números aleatórios del 1 al 100
arr_3d = np.random.randint(1,100,(27)).reshape(3,3,3)
arr_3d

array([[[39, 63, 86],
        [81, 94, 47],
        [22, 51, 66]],

       [[53, 84, 89],
        [86, 44, 32],
        [26, 58,  7]],

       [[21, 10,  2],
        [19, 22, 40],
        [11, 81, 41]]], dtype=int32)

In [64]:
# array 4D de números aleatorios en columnas de 4 elementos
arr_4d = np.random.randint(1,100,(256)).reshape(4,4,4,4)
arr_4d

array([[[[94, 28, 36, 77],
         [52, 88, 44, 57],
         [ 3, 57, 96, 68],
         [46, 47, 29, 23]],

        [[32, 52, 23, 16],
         [94, 31, 21, 52],
         [67, 22, 91, 15],
         [81, 92, 42, 55]],

        [[48, 75, 61, 10],
         [58, 32, 40, 28],
         [28, 79, 38, 14],
         [16, 54,  9, 84]],

        [[93, 18, 34, 92],
         [ 8, 69, 67, 49],
         [99, 18, 33, 79],
         [17, 56, 34, 56]]],


       [[[67, 40, 81, 28],
         [64, 13, 27, 12],
         [56, 42, 91, 73],
         [17, 56, 76, 19]],

        [[24, 34,  5, 32],
         [94, 79, 85, 14],
         [14, 17, 66, 14],
         [41, 84, 29, 89]],

        [[14,  2, 89,  3],
         [19, 96, 44, 74],
         [65, 99, 85, 63],
         [37, 14, 30, 61]],

        [[88, 33, 66, 52],
         [72, 86, 54, 58],
         [ 3, 54, 10, 81],
         [79, 97, 22, 92]]],


       [[[63, 88, 65, 64],
         [69, 34, 20, 32],
         [60, 63,  1, 73],
         [31, 59, 33, 17]],

      