In [70]:
# Arrays y persistencia

- Método binario (almacena en codigo binario, no podemos editar directamente)
- Método texto (alamcena en txt, podemos editar el txt)

## Método binario

In [71]:
import numpy as np

# creamos un array aleatorio de números enteros de dos dimensiones
arr_1 = np.random.randint(0,4,[3,3])

arr_1

array([[1, 2, 1],
       [1, 0, 1],
       [2, 0, 2]], dtype=int32)

In [72]:
# guardando binario
np.save('arr_1.npy', arr_1) # de momento en memoria ( se pone la ruta)

In [73]:
del(arr_1)
arr_1 # da error si está borrada

NameError: name 'arr_1' is not defined

In [ ]:
# cargamos la array del archivo binario en memoria
arr_1 = np.load('arr_1.npy')
arr_1

array([[2, 2, 3],
       [3, 1, 1],
       [2, 2, 1]], dtype=int32)

En archivos binarios podemos guardar y recuperar barios arrays a la vez

In [ ]:
# creamos una segunda array
arr_2 = np.random.randint(-4, 0, [3,3])
arr_2

array([[-3, -1, -4],
       [-2, -3, -1],
       [-4, -2, -1]], dtype=int32)

In [ ]:
# usamos la extención .npz como archivo comprimido
# creams una clave para cada array que queramos guardar
arr_1
np.savez('arrays.npz', arr_1= arr_1, arr_2= arr_2)

In [ ]:
del(arr_1)
del(arr_2)

In [ ]:
# cargamos el archivo binario
arrays = np.load('arrays.npz')
arrays
# El archivo binario es archivo npz con dos claves y las podemos recuperar por clave guardado

NpzFile 'arrays.npz' with keys: arr_1, arr_2

In [ ]:
# recuperamos la array 
arrays['arr_1']

array([[2, 2, 3],
       [3, 1, 1],
       [2, 2, 1]], dtype=int32)

In [ ]:
arrays['arr_2']

array([[-3, -1, -4],
       [-2, -3, -1],
       [-4, -2, -1]], dtype=int32)

## Guardado en texto

- Para guardar vamos a usar **savetxt()**
- Para cargar **loadtxt()**

In [74]:
# creamos un array de prueba
arr_3 = np.random.randint(-10, 10, [3,3])

In [75]:
# guardamos en un archivo de texto
np.savetxt('arr_3.txt', arr_3) # el separador por defecto es un espacio 

In [78]:
# cambiamos el separador de columnas
np.savetxt('arr_3.txt', arr_3, delimiter=',') # para separar por comas


In [79]:
del(arr_3) # aqui peta porque lo borra de memoria
arr_3

NameError: name 'arr_3' is not defined

In [80]:
# recuperamos usando el delimitador
arr_3 = np.loadtxt('arr_3.txt', delimiter= ',')

arr_3

array([[ 7., -3., -1.],
       [ 0., -1., -2.],
       [ 4.,  8.,  7.]])