# Ejercicios

## Ejercicio 1

1) Crea dos arrays de Numpy de tamaño 10 con números aleatorios entre 1 y 100. realiza las siguientes operaciones:

- Suma los dos arrays
- Resta el segundo array del primero
- Multiplica los dos arrays
- Divide el primer array por el segundo
- Encuentra el máximo y el mínimo de cara array

In [9]:
import numpy as np

arr_1 = np.random.randint(1,100, 10)
arr_2 = np.random.randint(1,100, 10)
print('Array 1')
print(arr_1)
print('Array 2')
print(arr_2)

# Suma
print('Suma')
print(arr_1 + arr_2)

# Resta
print('Resta')
print(arr_1 - arr_2)

# Multiplicación
print('Multiplicación')
print(arr_1 * arr_2)

# División
print('División')
print(arr_1 / arr_2)

# Máximos y mínimos
print('Máximo array 1')
print(arr_1.max())
print('Máximo array 2')
print(arr_2.max())
print('Mínimo array 1')
print(arr_1.min())
print('Máínimo array 2')
print(arr_2.min())

Array 1
[15 10 10 39 14 25 54 97  4 74]
Array 2
[51  2 37  2  7 86  5 50 59 15]
Suma
[ 66  12  47  41  21 111  59 147  63  89]
Resta
[-36   8 -27  37   7 -61  49  47 -55  59]
Multiplicación
[ 765   20  370   78   98 2150  270 4850  236 1110]
División
[ 0.29411765  5.          0.27027027 19.5         2.          0.29069767
 10.8         1.94        0.06779661  4.93333333]
Máximo array 1
97
Máximo array 2
86
Mínimo array 1
4
Máínimo array 2
2
