# Ejercicios

## Ejercicio 1

1) Crea dos arrays de Numpy de tamaño 10 con números aleatorios entre 1 y 100. realiza las siguientes operaciones:

- Suma los dos arrays
- Resta el segundo array del primero
- Multiplica los dos arrays
- Divide el primer array por el segundo
- Encuentra el máximo y el mínimo de cara array

In [9]:
import numpy as np

arr_1 = np.random.randint(1,100, 10)
arr_2 = np.random.randint(1,100, 10)
print('Array 1')
print(arr_1)
print('Array 2')
print(arr_2)

# Suma
print('Suma')
print(arr_1 + arr_2)

# Resta
print('Resta')
print(arr_1 - arr_2)

# Multiplicación
print('Multiplicación')
print(arr_1 * arr_2)

# División
print('División')
print(arr_1 / arr_2)

# Máximos y mínimos
print('Máximo array 1')
print(arr_1.max())
print('Máximo array 2')
print(arr_2.max())
print('Mínimo array 1')
print(arr_1.min())
print('Máínimo array 2')
print(arr_2.min())

Array 1
[15 10 10 39 14 25 54 97  4 74]
Array 2
[51  2 37  2  7 86  5 50 59 15]
Suma
[ 66  12  47  41  21 111  59 147  63  89]
Resta
[-36   8 -27  37   7 -61  49  47 -55  59]
Multiplicación
[ 765   20  370   78   98 2150  270 4850  236 1110]
División
[ 0.29411765  5.          0.27027027 19.5         2.          0.29069767
 10.8         1.94        0.06779661  4.93333333]
Máximo array 1
97
Máximo array 2
86
Mínimo array 1
4
Máínimo array 2
2


In [2]:
# Profe
import numpy as np

# creamos dos arrays de tamaño 10 con num aleatorios entre 1 y 100
array1 = np.random.randint(1,101, size=10)
array2 = np.random.randint(1,101, size=10)

print(array1)
print(array2)

#operaciones
suma = np.add(array1, array2)
resta = np.subtract(array2, array1)
multi = np.multiply(array1, array2)
divi = np.divide(array1, array2)

# max y min
max_array1 = np.max(array1)
min_array1 = np.min(array1)
max_array2 = np.max(array2)
min_array2 = np.min(array2)

# salida
print(f'Array1: {array1}')
print(f'Array2: {array2}')
print(f'Suma: {suma}')
print(f'Resta: {resta}')
print(f'Multipl: {multi}')
print(f'Divis: {divi}')
print(f'Max array1: {max_array1}')
print(f'Min array1: {min_array1}')
print(f'Max array2: {max_array2}')
print(f'Min array2: {min_array2}')

[ 33  56   7 100   4  34   2  37   2  30]
[52 46 54 40 12 55  4  8 45  4]
Array1: [ 33  56   7 100   4  34   2  37   2  30]
Array2: [52 46 54 40 12 55  4  8 45  4]
Suma: [ 85 102  61 140  16  89   6  45  47  34]
Resta: [ 19 -10  47 -60   8  21   2 -29  43 -26]
Multipl: [1716 2576  378 4000   48 1870    8  296   90  120]
Divis: [0.63461538 1.2173913  0.12962963 2.5        0.33333333 0.61818182
 0.5        4.625      0.04444444 7.5       ]
Max array1: 100
Min array1: 2
Max array2: 55
Min array2: 4


## Ejercicio 2

Crea un array de 100 números aleatorios con una distribución normal (media=0, desviacion estándar=1). Luego realiza las siguientes tareas:
1. Calcular la media y la desviacion estandar del array
2. Filtra los elementos que son mayores que 1.
3. Encuentra el valor máximo y minimo del array filtrado

In [3]:
import numpy as np
print('Array:')
arr_3 = np.random.normal(size=100)
print(arr_3)
print(f'\nMedia:')
print(arr_3.mean())
print(f'\nDesviación estandar:')
print(arr_3.std())
print(f'\nElementos mayores que 1:')
arr_4 =np.where(arr_3 <1, 0, arr_3)
print(arr_4)
arr_4 =np.where(arr_3 <1, arr_3.mean(), arr_3)
print(f'\nValor máximo y mínimo del array filtrado:')
print(arr_4.max())
print(arr_4.min())

Array:
[ 0.24032716 -2.86666198  0.85384724  0.01418937 -0.28889335  1.85291949
 -0.30688381  0.14549461  0.19666231  0.06826678  0.56440157  0.46105033
 -0.45376625  1.10105135  1.71173625 -0.50780443 -1.56217185 -0.22405737
 -0.41729436 -0.97205598  2.10761818 -1.04700831  0.74770552 -1.82386498
  2.65068461 -0.46327549 -0.32977448  0.18629437  0.22349076 -0.32723217
 -0.65901833 -0.01740928  1.39323891  0.93171407  0.82001691  1.03741447
 -0.21365014  0.61532051  1.06333144 -1.38178603  1.56334633 -2.03225009
 -0.64904789 -0.83523624 -0.21111817  0.04263789 -0.93246045  2.5508652
  0.48066957 -0.90940338 -0.10219763  2.35911286  0.51769373  0.17129628
  0.81725316 -0.02720131  0.81369484  0.21869945 -1.19354264 -0.62857918
  0.72720146  1.08354726  0.97515052 -2.14122529 -0.39038251  0.63768905
 -1.52219931  0.90455769  0.63203206 -1.38064143 -1.31610672 -2.3946111
  1.42124313 -0.20137181  0.11139141 -1.05396803 -1.85497165 -0.13903018
  0.06088123 -1.07661817  0.75184589 -2.593448

In [4]:
# Profe
import numpy as np

# creamos el array
array = np.random.normal(loc= 0, scale=1, size=100)

# calculamos la media y la desviacion estandar
media = np.mean(array)
desv_stand = np.std(array)

# Filtramos los elementos mayores que 1 (los dos métodos hacen lo mismo)

indice = np.where(array>1)
filtro1 = array[indice]

filtro2= array[array>1]

# Calculamos el valor máximo y el valor mínimo del array filtrado
max_filtro = np.max(filtro2)
min_filtro = np.min(filtro1)

# salida

print(f'Array original: {array}')
print(f'Media array original: {media}')
print(f'Desviación estandar array original: {desv_stand}')
print(f'Elementos mayores que 1: {filtro1}')
print(f'Max array filtrado: {max_filtro}')
print(f'Min array filtrado: {min_filtro}')

Array original: [-0.39241417 -0.92682756  0.32617031  1.09751655 -0.60919056  0.53835549
 -1.08533511  1.58013719  2.38059921  1.16799212 -1.89914973 -1.09306787
 -1.13609055 -0.36108656  1.79052712 -0.03334599 -0.11434584 -1.32892871
 -0.31713961 -0.133822   -0.3148317   1.93929543 -0.4154916  -0.16327861
  1.27410275  0.04215323 -0.29516279 -1.76299849 -0.08365004 -1.1906508
  0.23194484  1.0187596   0.29956564 -1.29716862 -0.98174913  0.9348366
  1.2506033  -1.07208226  0.32103526  0.23583849 -0.69098336 -0.47927372
 -1.24075939 -0.68285011  2.73958708  1.02243863  0.95541153  1.02710186
  0.31024458  1.4635611   0.15685127  0.07661729 -0.42865013  1.41571631
 -1.41654183  0.77622567  0.69641476 -1.28961885  1.63124706  0.14825202
 -0.23185081  0.95174733 -0.25516995 -0.31133753  0.45933833 -0.10131353
 -1.03528696 -0.3271595   2.65860097 -0.8820369  -0.93175108 -0.32690062
 -0.52181535 -0.25457172 -0.6071533  -0.61284551 -0.07990291 -0.11612735
 -0.67240785  0.22418543  0.4042874  