# Ejercicios

## Ejercicio 1

1) Crea dos arrays de Numpy de tamaño 10 con números aleatorios entre 1 y 100. realiza las siguientes operaciones:

- Suma los dos arrays
- Resta el segundo array del primero
- Multiplica los dos arrays
- Divide el primer array por el segundo
- Encuentra el máximo y el mínimo de cara array

In [9]:
import numpy as np

arr_1 = np.random.randint(1,100, 10)
arr_2 = np.random.randint(1,100, 10)
print('Array 1')
print(arr_1)
print('Array 2')
print(arr_2)

# Suma
print('Suma')
print(arr_1 + arr_2)

# Resta
print('Resta')
print(arr_1 - arr_2)

# Multiplicación
print('Multiplicación')
print(arr_1 * arr_2)

# División
print('División')
print(arr_1 / arr_2)

# Máximos y mínimos
print('Máximo array 1')
print(arr_1.max())
print('Máximo array 2')
print(arr_2.max())
print('Mínimo array 1')
print(arr_1.min())
print('Máínimo array 2')
print(arr_2.min())

Array 1
[15 10 10 39 14 25 54 97  4 74]
Array 2
[51  2 37  2  7 86  5 50 59 15]
Suma
[ 66  12  47  41  21 111  59 147  63  89]
Resta
[-36   8 -27  37   7 -61  49  47 -55  59]
Multiplicación
[ 765   20  370   78   98 2150  270 4850  236 1110]
División
[ 0.29411765  5.          0.27027027 19.5         2.          0.29069767
 10.8         1.94        0.06779661  4.93333333]
Máximo array 1
97
Máximo array 2
86
Mínimo array 1
4
Máínimo array 2
2


## Ejercicio 2

Crea un array de 100 números aleatorios con una distribución normal (media=0, desviacion estándar=1). Luego realiza las siguientes tareas:
1. Calcular la media y la desviacion estandar del array
2. Filtra los elementos que son mayores que 1.
3. Encuentra el valor máximo y minimo del array filtrado

In [10]:
import numpy as np
print('Array:')
arr_3 = np.random.normal(size=100)
print(arr_3)
print(f'\nMedia:')
print(arr_3.mean())
print(f'\nDesviación estandar:')
print(arr_3.std())
print(f'\nElementos mayores que 1:')
arr_4 =np.where(arr_3 <1, arr_3.mean(), arr_3)
print(arr_4)
print(f'\nValor máximo y mínimo del array filtrado:')
print(arr_4.max())
print(arr_4.min())


Array:
[ 0.48252579  1.19812535 -0.78360306  0.98924344  0.78663116  0.23402423
 -0.94573764 -0.28833041  1.01868411  0.50558618 -0.46831188  0.23828616
 -1.38846876  1.51600082  0.72612473  1.38742716 -0.70614962  0.88323852
  1.14034785 -1.82990953 -0.82564823  0.78908864  0.60751659  0.85193549
 -0.82041672 -0.89760996  0.56186646 -1.07818235 -0.57662721 -0.27513733
 -1.69133225  1.5123644   0.0048732   0.70404996 -0.40701986 -0.64013965
 -0.63634193  0.56247468 -0.92617143  2.04263425  0.8112732  -1.31467196
  0.57687588  3.25043891  0.34243516 -1.49916125 -0.02063941 -0.78394055
 -1.07216983  0.99290408 -0.88187917  0.11697253  0.74712781 -1.96525248
  1.03766529  1.19812837  0.87287844  1.40980194  0.02493973  0.23828459
 -0.93573505  0.07765917 -0.63698921 -2.1972564  -0.03620181  1.39349735
  0.75814328 -0.28405787  1.54027946  0.12068992 -0.99599748  0.41430926
  0.85679356 -0.80655038  0.48051555 -0.5012733  -1.16960975 -0.04978303
 -0.98125591 -0.43033338  0.01992443 -0.0833